name: Build binary artifacts

on:
  push:
    tags:
      - weekly.**
      - 0.**
      
permissions:
  contents: write

jobs:

  build-linux:
    runs-on: ubuntu-20.04
    env:
      ZIPNAME: goose_linux.zip
    steps:
      - uses: actions/checkout@master
        with:
          submodules: true

      - uses: haskell/actions/setup@v2
        with:
          ghc-version: '8.10.7'
          cabal-version: '3.10'
      - name: Compile
        run: |
          cabal build
      - name: Create ZIP archive
        run: |
          find dist-newstyle -type f -name 'goose' -exec mv '{}' goose \;
          zip -r $ZIPNAME goose std README.md
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: goose_linux.zip
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          GITHUB_REPOSITORY: goose-language/goose

  build-macos:
    runs-on: macos-latest
    env:
      ZIPNAME: goose_macos.zip
    steps:
      - uses: actions/checkout@master
        with:
          submodules: true

      - name: Install system dependencies (macOS)
        run: |
          brew install libsodium gmp llvm@12
          echo "/usr/local/opt/llvm@12/bin" >> $GITHUB_PATH

      - uses: haskell/actions/setup@v2
        with:
          ghc-version: '8.10.7'
          cabal-version: '3.10'
      - name: Compile
        run: |
          cabal build
      - name: Create ZIP archive
        run: |
          find dist-newstyle -type f -name 'goose' -exec mv '{}' goose \;
          zip -r $ZIPNAME goose std README.md
      - name: Create artifact
        uses: actions/upload-artifact@v2
        with:
          name: macos
          path: goose_macos.zip
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: goose_macos.zip
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          GITHUB_REPOSITORY: goose-language/goose

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@master
        with:
          submodules: true
      - name: Setup LLVM using Chocolatey
        uses: crazy-max/ghaction-chocolatey@v2.1.0
        with:
          args: install llvm --version=12.0.0 --allow-downgrade --force --yes
      - uses: haskell/actions/setup@v2
        with:
          ghc-version: '8.10.7'
          cabal-version: '3.10'
      - name: Compile
        run: |
          cabal build
      - name: Create ZIP archive
        run: |
          Get-ChildItem -Filter goose.exe -Recurse $pwd | Foreach {mv $_.fullname goose.exe}
          Compress-Archive -CompressionLevel Optimal -Force -Path goose.exe, std, README.md -DestinationPath goose_windows.zip
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: goose_windows.zip
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          GITHUB_REPOSITORY: goose-language/goose
