on:
  release:
    types: [published]
jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    
    name: Build Goose
    steps:
      - uses: actions/checkout@master
      - uses: haskell/actions/setup@v1.2
        with:
          ghc-version: 9.4.2
          cabal-version: 3.0
      
      - name: Compile and ZIP Goose on Unix
        if: matrix.platform != 'windows-latest'
        run: |
          cabal build
          find dist-newstyle -type f -name 'goose' -exec mv '{}' goose \;
          zip -r 'goose-${{ matrix.platform }}.zip' goose library README.md
          
      - name: Compile and ZIP Goose on Windows
        if: matrix.platform == 'windows-latest'
        run: |
          cabal build
          Get-ChildItem -Filter goose.exe -Recurse $pwd | Foreach {mv $_.fullname goose.exe}
          Compress-Archive -CompressionLevel Optimal -Force -Path goose.exe, library, README.md -DestinationPath 'goose-${{ matrix.platform }}.zip' 
        
      - uses: AButler/upload-release-assets@v2.0
        with:
          files: './goose-${{ matrix.platform }}.zip'
          repo-token: ${{ secrets.GITHUB_TOKEN }}